testnetName: "mina-testnet"
mina:
  runtimeConfig:
  generateGenesisProof: true
  image: minaprotocol/mina-daemon:0.0.12-beta-develop-589b507
  seedPeers:
    - /ip4/35.185.66.37/tcp/10105/p2p/12D3KooWQ7Pz3SPizarzx9ZhCJ6jNmQ2iDPgHQxVzRzqYU2SgRSd
    - /ip4/35.237.214.144/tcp/10120/p2p/12D3KooWGtjWnCcvkaSEbKuNbPivEogxqtLWcsJiQtURydptvrsA
  ports:
    client: "8301"
    graphql: "3085"
    metrics: "10001"
    p2p: "10909"

seed:
  name: "seed-node"
  externalIp: 1.1.1.1
  nodePort: 30085
  privateKey:
    active: false
    isSecretManager: true
    secretName: ""
  libp2p:
    active: false
    isSecretManager: true
    secretName: ""
    password: ""
    pub: ""

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 5
  initialDelaySeconds: 30

nodeSelector:
  preemptible: false

gcloud: 
  keyfile: ""
  uploadBlocks: true
  uploadBucket: "mina_network_block_data"