apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "archive-node.fullname" . }}
  labels:
    app: {{ template "archive-node.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "archive-node.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "archive-node.fullname" . }}
        testnet: {{ .Values.testnetName }}
        role: archive-node
        version: {{ trunc 6 (split ":" .Values.mina.image)._1 | trimSuffix "-" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.mina.ports.metrics | quote }}
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: mina
        resources:
          limits:
          requests:
            memory: 6.0Gi
            cpu: 3.0
        image: {{ $.Values.mina.image }}
        args: [ "daemon",
          "-log-level", {{ .Values.mina.logLevel }},
          "-log-json",
          {{- if .Values.mina.logSnarkWorkGossip }}
          "-log-snark-work-gossip", "true",
          {{- end -}}
          {{- range .Values.mina.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end -}}
          {{- if .Values.mina.enableFlooding }}
          "-enable-flooding true"
          {{- end -}}
          {{- if .Values.mina.peerExchange }}
          "-peer-exchange true"
          {{- end -}}
          {{- range .Values.mina.directPeers }}
          "-direct-peers", {{ . | quote }},
          {{- end -}}
          {{- if .Values.mina.seedPeersURL }}
          "-peer-list-url", {{ .Values.mina.seedPeersURL | quote }},
          {{- end -}}
          "-config-directory", "/root/.mina-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-insecure-rest-server",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-archive-address", "$(DAEMON_ARCHIVE_PORT)",
          {{- if .Values.mina.runtimeConfig }}
          "-config-file", "/config/daemon.json",
          {{- end -}}
          "-generate-genesis-proof", {{ .Values.mina.generateGenesisProof | quote }}
        ]
        env:
        - name: DAEMON_REST_PORT
          value: {{ .Values.mina.ports.graphql | quote }}
        - name: DAEMON_ARCHIVE_PORT
          value: {{ .Values.archive.ports.server | quote }}
        - name: DAEMON_CLIENT_PORT
          value: {{ .Values.mina.ports.client | quote }}
        - name: DAEMON_METRICS_PORT
          value: {{ .Values.mina.ports.metrics | quote }}
        - name: DAEMON_EXTERNAL_PORT
          value: {{ .Values.mina.ports.p2p | quote }}
        - name: mina_CLIENT_TRUSTLIST
          value: "10.0.0.0/8"
        - name: CONNECT_PRIVATE_IPS
          value: "true"
        ports:
        - name: client-port
          protocol: TCP 
          containerPort: {{ .Values.mina.ports.client }}
        - name: graphql-port
          protocol: TCP 
          containerPort: {{ .Values.mina.ports.graphql }}
        - name: metrics-port
          protocol: TCP 
          containerPort: {{ .Values.mina.ports.metrics }}
        - name: external-port
          protocol: TCP 
          containerPort: {{ .Values.mina.ports.p2p }}
          hostPort: {{ .Values.mina.ports.p2p }}
{{- include "healthcheck.daemon.allChecks" .Values | indent 8 }}
        imagePullPolicy: Always
        volumeMounts: 
        - name: config-dir
          mountPath: /root/.mina-config
        {{- if .Values.mina.runtimeConfig }}
        - name: daemon-config
          mountPath: "/config/"
        {{- end }}
      # Rosetta Process
      - name: rosetta
        resources:
          limits:
          requests:
            memory: 2.0Gi
            cpu: 0.1
        image: {{ $.Values.rosetta.image }}
        command: ["mina-rosetta"]
        args: [
          "--port", "{{ .Values.rosetta.ports.web }}",
          "--graphql-uri", "{{ .Values.rosetta.graphqlUri }}",
          "--archive-uri", "{{ tpl .Values.archive.postgresUri . }}"
        ]
        ports:
        - name: web-port
          protocol: TCP 
          containerPort: {{ .Values.rosetta.ports.web }}
        imagePullPolicy: Always
      # Archive Process
      - name: archive
        image: {{ .Values.archive.image }}
        args: [ 
          "coda-archive",
          "run",
          "-postgres-uri", "{{ tpl .Values.archive.postgresUri . }}",
          {{- if .Values.mina.runtimeConfig }}
          "-config-file", "/config/daemon.json",
          {{- end }}
          "-server-port", "{{ .Values.archive.ports.server }}"
        ]
        env:
        imagePullPolicy: Always
        {{- if .Values.mina.runtimeConfig }}
        volumeMounts:
        - name: daemon-config
          mountPath: "/config/"
        {{- end }}
        ports:
        - name: archive-port
          protocol: TCP
          containerPort: {{ .Values.archive.ports.server }}
        - name: postgres-port
          protocol: TCP
          containerPort: {{ .Values.archive.ports.postgres }}
{{- include "healthcheck.archive.allChecks" . | indent 8 }}
{{- include "nodeSelector.preemptible" .Values | indent 6 }}
      volumes:
      - name: config-dir
        emptyDir: {}
      {{- if .Values.mina.runtimeConfig }}
      - name: daemon-config
        configMap:
          name: "{{ template "archive-node.fullname" . }}-daemon-config"
      {{- end }}