{{- if $.Values.mina.runtimeConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "archive-node.fullname" . }}-daemon-config"
  labels:
    app: {{ template "archive-node.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ $.Values.mina.runtimeConfig | quote }}
{{- end }}
