apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.seed.name }}
  labels:
    app: {{ $.Values.seed.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.seed.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.seed.name }}
        testnet: {{ $.Values.testnetName }}
        role: seed
        version: {{ trunc 6 (split ":" $.Values.mina.image)._1 | trimSuffix "-" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ $.Values.mina.ports.metrics | quote }}
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      {{- if and ($.Values.seed.privateKey.active) ($.Values.seed.privateKey.isSecretManager) }}
      - name: download-private-key
        image: {{ $.Values.mina.image | quote }}
        command: 
        - bash
        - -c 
        - gcloud auth activate-service-account --key-file /gcloud/keyfile.json && gcloud --project $(cat /gcloud/keyfile.json | jq -r '.project_id') secrets versions access latest  --secret {{ $.Values.seed.privateKey.secretName }} >> /keys/key
        env: 
          - name: GCLOUD_KEYFILE
            value: "/gcloud/keyfile.json"
        volumeMounts: 
        - name: private-keys
          mountPath: "/keys/"
        - name: gcloud-keyfile
          mountPath: "/gcloud/"
      {{- end }}
      {{- if and ($.Values.seed.libp2p.isSecretManager) ($.Values.seed.libp2p.active) }}
      - name: download-libp2p-key
        image: {{ $.Values.mina.image | quote }}
        command: 
        - bash
        - -c 
        - gcloud auth activate-service-account --key-file /gcloud/keyfile.json && gcloud --project $(cat /gcloud/keyfile.json | jq -r '.project_id') secrets versions access latest  --secret {{ $.Values.seed.libp2p.secretName }} >> /libp2p-keys/key
        env: 
          - name: GCLOUD_KEYFILE
            value: "/gcloud/keyfile.json"
        volumeMounts: 
        - name: libp2p-keys
          mountPath: /libp2p-keys
        - name: gcloud-keyfile
          mountPath: "/gcloud/"
      {{- end }}
      {{ if $.Values.seed.libp2p.active -}}
      - name: libp2p-perms
        image: {{ $.Values.mina.image | quote }}
        command:
        - bash
        - -c
        - /bin/cp /libp2p-keys/* /root/libp2p-keys && /bin/chmod -R 0700 /root/libp2p-keys/
        volumeMounts:
        - name: libp2p-keys
          mountPath: /libp2p-keys
        - name: actual-libp2p
          mountPath: /root/libp2p-keys
      {{- end }}
      containers:
      - name: mina
        resources:
          limits:
          requests:
            memory: 6.0Gi
            cpu: 3.5
        image: {{ $.Values.mina.image }}
        args: [ "daemon",
          "-log-level", "Debug",
          "-log-precomputed-blocks", "true",
          "-log-json",
          "-log-snark-work-gossip", "true",
          "-config-directory", "/root/.mina-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-enable-peer-exchange", "true",
          {{- if $.Values.mina.seedPeersURL }}
          "-peer-list-url", {{ $.Values.mina.seedPeersURL | quote }},
          {{- end -}}
          {{- if $.Values.mina.runtimeConfig }}
          "-config-file", "/config/daemon.json",
          {{- end }}
          {{- if $.Values.seed.libp2p.active }}
          "-discovery-keypair", "/root/libp2p-keys/key",
          {{- end -}}
          {{- range $.Values.mina.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end }}
          "-generate-genesis-proof", {{ $.Values.mina.generateGenesisProof | quote }},
          {{- if $.Values.mina.uploadBlocksToGCloud }}
          "-upload-blocks-to-gcloud", "true",
          {{- end }}
          "-seed"
        ]
        env:
        - name: "RAYON_NUM_THREADS"
          value: "6"
        - name: DAEMON_REST_PORT
          value: {{ $.Values.mina.ports.graphql | quote }}
        - name: DAEMON_CLIENT_PORT
          value: {{ $.Values.mina.ports.client | quote }}
        - name: DAEMON_METRICS_PORT
          value: {{ $.Values.mina.ports.metrics | quote }}
        - name: mina_CLIENT_TRUSTLIST
          value: "10.0.0.0/8"
        - name: CONNECT_PRIVATE_IPS
          value: "true"
        - name: DAEMON_EXTERNAL_PORT
          value: {{ $.Values.mina.ports.p2p | quote }}
        {{- if and ($.Values.seed.libp2p.password) ($.Values.seed.libp2p.active) }}
        - name: CODA_LIBP2P_PASS
          value: {{ $.Values.seed.libp2p.password | quote }}
        {{- end }}
        {{- if $.Values.gcloud.uploadBlocks }}
        - name: GCLOUD_BLOCK_UPLOAD_BUCKET
          value: {{ $.Values.gcloud.uploadBucket| quote }}
        - name: NETWORK_NAME
          value: {{ $.Values.testnetName | quote }}
        {{- end }}
        ports:
        - name: client-port
          protocol: TCP 
          containerPort: {{ $.Values.mina.ports.client }}
        - name: graphql-port
          protocol: TCP 
          containerPort: {{ $.Values.mina.ports.graphql }}
        - name: metrics-port
          protocol: TCP 
          containerPort: {{ $.Values.mina.ports.metrics }}
        - name: external-port
          protocol: TCP 
          containerPort: {{ $.Values.mina.ports.p2p }}
          hostPort: {{ $.Values.mina.ports.p2p }}
{{- include "healthcheck.seed.allChecks" $.Values | indent 8 }}
        imagePullPolicy: Always
        volumeMounts:
        {{- if $.Values.seed.libp2p }}
        - name: actual-libp2p
          mountPath: /root/libp2p-keys
        {{- end }}
        {{- if $.Values.mina.uploadBlocksToGCloud }}
        - name: gcloud-keyfile
          mountPath: "/gcloud/"
        {{- end }}
        {{- if $.Values.mina.runtimeConfig }}
        - name: daemon-config
          mountPath: "/config/"
        {{- end }}
      volumes:
      {{- if $.Values.mina.runtimeConfig }}
      - name: daemon-config
        configMap:
          name: seed-daemon-config
      {{- end }}
      {{- if and ($.Values.seed.privateKey.active) (eq $.Values.seed.privateKey.isSecretManager false) }}
      - name: private-keys
        secret:
          secretName: {{ $.Values.seed.privateKey.secretName }}
          defaultMode: 256
          items:
          - key: key
            path: key
          - key: pub
            path: key.pub
      {{- else }}
      - name: private-keys
        emptyDir: {}
      {{- end}}
      {{- if and (eq $.Values.seed.libp2p.isSecretManager false) ($.Values.seed.libp2p.active) }}
      - name: libp2p-keys
        secret:
          secretName: {{ $.Values.seed.libp2p.secretName }}
          defaultMode: 0700
          items:
          - key: key
            path: key
          - key: pub
            path: key.pub
      {{- else }}
      - name: libp2p-keys
        emptyDir: {}
      {{- end }}

      {{- if $.Values.gcloud.uploadBlocks }}
      - name: gcloud-keyfile
        secret:
          secretName: gcloud-keyfile
          defaultMode: 256
          items:
          - key: keyfile
            path: keyfile.json
      {{- end }}
      - name: actual-libp2p
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.seed.name }}
spec:

  clusterIP: None

  # We want all pods to have their addresses published for the sake of the
  # other testnet pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  selector:
    app: {{ $.Values.seed.name }}
  ports:
  - name: tcp-p2p
    port: {{ $.Values.mina.ports.p2p }}
    targetPort: external-port

{{- if $.Values.seed.externalIp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.seed.name }}-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.seed.externalIp }}
  
  # We want all pods to have their addresses published for the sake of the
  # other testnet pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  selector:
    app: {{ $.Values.seed.name }}
  ports:
  - name: tcp-p2p
    port: {{ $.Values.mina.ports.p2p }}
    targetPort: external-port
    nodePort: {{ $.Values.seed.nodePort }}
{{end}}